apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-k8s-demo
  name: node-k8s-demo
  namespace: dmalvia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-k8s-demo
  strategy: {}
  template:
    metadata:
      labels:
        app: node-k8s-demo
    spec:
      containers:
      - image: obekegodfreyvicent/node-k8s-demo:latest
        name: node-k8s-demo
        ports:
        - containerPort: 3000
        resources: {}
status: {}
