apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-k8s-demo
  name: node-k8s-demo
  namespace: dmalvia
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-k8s-demo
  type: LoadBalancer
status:
  loadBalancer: {}
